### ISSUE TITLE
Fall back to canvas when WebGL is not supported

### ISSUE THREAD

**Issue by anissen** [gre/deprecated-glsl.js#9]
If would be nice if glsl.js would automatically fall back to its standard no-WebGL canvas version when WebGL is not supported. 
In doing so glsl.js could be used to spice up canvas animations on browsers that support WebGL while still offering a plain canvas animation for other browsers.

**Comment by gre** [comment]
Are you referring to games like the snake example? When you have one canvas 2d for drawing and a canvas webgl for post-processing?

If so, it is not fixable in the library itself, glsl.js is a tiny toolkit on top of GLSL, using a canvas2d with it is already a specific use-case.

But you can easily solve that in different ways, here is one:
put the 2 canvas one on top of the other :)

``` css
canvas#2d {
  position: absolute;
  top: 0;
  bottom: 0;
  z-index: 1;
}
canvas#webgl {
  position: absolute;
  top: 0;
  bottom: 0;
  z-index: 2;
}
```

Then check for support:

``` javascript
// ... do your canvas #2d work
if (Glsl.supported()) {
  // Do your Glsl({ .. }) with the canvas #webgl
}
```

A canvas is transparent by default, so it should make the 2d canvas visible if you don't use it.
